### PR TITLE
wandb v0.17.4

### PR DESCRIPTION
**Pull request by Jn58**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

#### 1. Update wandb version
Update wandb version from 0.16.6 to 0.17.4.
#### 2. Update source URL
Wandb no longer distributes the source from PyPI. Therefore, change the URL from PyPI to GitHub.
#### 3. Add build requirements
Add following packages for building wandb:
- hatchling
- typing_extensions
- go
- gcc
#### 4. Add test requirements
Add following package for testing wandb:
- platformdirs

### CODE REVIEW

**Comment by Jn58** [comment]
I've discovered that I used the wrong directive in the requirements. I am currently working on fixing it.

**Comment by Jn58** [comment]
Move `gcc` and `go` from `requirements-host` to `requirements-build`, and replace `gcc` with `{{ compiler('c') }}`.

**Comment by desilinguist** [comment]
Thank you for this PR! We have been waiting for conda-forge to catch up with PyPI!

**Comment by Jn58** [comment]
I am closing this PR to reopen it with new maintainers added as reviewers and to squash the messy commits.

**Comment by Jn58** [comment]
New PR #108

**Pull request closed without merging**
